### ISSUE TITLE
Can't launch django server

### ISSUE THREAD

**Issue by DorianMoreno** [CapituloJaverianoACM/ACMWebSite#41]
**Describe the bug**
RIght now the server can't be launched when trying to execute the project.

**To Reproduce**
1. Set up environment and dependencies
2. run: `python manage.py runserver`

**Additional context**
The objective is not to necesarilly get the server running, but to identify what is causing this problem and create an issue to solve it.

**Comment by juanpa097** [comment]
Can you provide some logs to have more info?
